{
    "title" : "503 - General SSLEngine problem",
    "uri" : "http://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "printableUri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "clickUri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "excerpt" : "We have installed CES on a remote server. ... On our Sitecore server, when trying to bring up the site http://sitecoreserver/coveo/rest, we are getting the following: ... As you can see, it thinks ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1112,
    "percentScore" : 75.03586,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "503 - General SSLEngine problem",
      "sysauthor" : "Ben",
      "sysurihash" : "Ys6yZ9g0wGYRQx4i",
      "urihash" : "Ys6yZ9g0wGYRQx4i",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160353,
      "questionaskeddatestring" : "·\n            Aug 21, 2015 at 04:11 PM ·",
      "tags" : [ "coveoforsitecore", "rest", "error" ],
      "sysconcepts" : "coveo ; serverCertificatePath ; sitecoreserver ; Windows service ; configs ; uri ; clientCertificatePath settings ; show differences ; control panel ; certificates ; SearchProvider ; CoveoSearchService",
      "concepts" : "coveo ; serverCertificatePath ; sitecoreserver ; Windows service ; configs ; uri ; clientCertificatePath settings ; show differences ; control panel ; certificates ; SearchProvider ; CoveoSearchService",
      "printableuri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942262000,
      "permanentid" : "3f941900a69d59b786178cbb919add80adc2ea216a1c28047016a4f42e9f",
      "syslanguage" : [ "English" ],
      "transactionid" : 160353,
      "title" : "503 - General SSLEngine problem",
      "date" : 1440115200000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Jean-François L'Heureux" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5447757,
      "numberofcomments" : 0,
      "size" : 73811,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578055,
      "acceptedanswers" : 1,
      "syssize" : 73811,
      "sysdate" : 1440115200000,
      "author" : "Ben",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>We have installed CES on a remote server. On our Sitecore server, when trying to bring up the site <a rel=\"nofollow\" href=\"http://sitecoreserver/coveo/rest,\">http://sitecoreserver/coveo/rest,</a> we are getting the following:</p> \n<pre><code> {\n   \"statusCode\": 503,\n   \"message\": \"Server is unavailable: (General SSLEngine problem to https://localhost:52810/7.0/CoveoSearchService,java.net.ConnectException: General SSLEngine problem to https://localhost:52810/7.0/CoveoSearchService)\",\n   \"type\": \"ServerUnavailableException\",\n   \"executionReport\": {\n     \"type\": \"RootReport\",\n     \"description\": \"\",\n     \"duration\": 0,\n     \"result\": \"(com.coveo.search.api.pipeline.PipelineContext@3a9d6b4,Query(null,null,null,null,null,List(relevancy),[],[],null,null,null,5,false,true,false,false,false,false,0,10,200,0,false,false,[]))\",\n     \"childs\": [\n       {\n         \"type\": \"QueryPipelineReport\",\n         \"description\": \"Resolve identities\",\n         \"duration\": 0,\n         \"result\": \"ArrayBuffer(UserId(extranet\\\\Anonymous,Sitecore Security Provider for SitecoreServer-sitename,User,None,None))\",\n         \"childs\": [\n           \n         ]\n       },\n       {\n         \"type\": \"QueryPipelineReport\",\n         \"description\": \"Preprocess Query\",\n         \"logs\": [\n           {\n             \"severity\": \"INFO\",\n             \"message\": \"Applied ranking statements: .\",\n             \"timestamp\": \"+0\"\n           },\n           {\n             \"severity\": \"INFO\",\n             \"message\": \"Applied top statements: .\",\n             \"timestamp\": \"+0\"\n           }\n         ],\n         \"duration\": 0,\n         \"result\": \"Query(null,null,null,null,null,List(relevancy),[],[],null,null,null,5,false,true,false,false,false,false,0,10,200,0,false,false,[])\",\n         \"childs\": [\n           \n         ]\n       }\n     ]\n   },\n   \"results\": [\n     \n   ]\n }\n\n</code></pre> \n<p>As you can see, it thinks the coveo search service is installed locally. In our Coveo.SearchProvider.config, the SearchServiceUri node is set to <code><SearchServiceUri>https://CESServer:52810/7.0/CoveoSearchService</SearchServiceUri></code></p> \n<p>If we try to bring up this url <a rel=\"nofollow\" href=\"https://CESServer:52810/7.0/CoveoSearchService\">https://CESServer:52810/7.0/CoveoSearchService</a> from our sitecore server, it works fine.</p> \n<p>Also, when running the Coveo configuration under control panel, when we change the sitecore credentials, we see the datetime of the Coveo.SearchProvider.config file change, but our new credentials never make it into the file.</p> \n<p>Network Service has access over the site folders. Comparisons between configs on working sites and the new site only show differences in server names. If we point an existing site to the new CES server we get the same error when navigating to <a rel=\"nofollow\" href=\"http://sitecoreserver/coveo/rest\">http://sitecoreserver/coveo/rest</a> . </p>\n                </div>",
      "sitemaplastmodified" : 1440115200000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942262000,
      "questionnumber" : 5861,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "Ben",
      "sitename" : "Answers",
      "sysrowid" : 5447757,
      "uri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "503 - General SSLEngine problem",
    "Uri" : "http://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "PrintableUri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "ClickUri" : "https://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/5861/503-general-sslengine-problem.html",
    "Excerpt" : "We have installed CES on a remote server. ... On our Sitecore server, when trying to bring up the site http://sitecoreserver/coveo/rest, we are getting the following: ... As you can see, it thinks ...",
    "FirstSentences" : null
  }