{
    "title" : "coveo for sitecore+An entry with the same key already exists",
    "uri" : "http://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "printableUri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "clickUri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "excerpt" : "coveo for sitecore+An entry with the same key already exists ... i am getting following exception.Actually there is one folder deleted from sitecore and recreated. ... after that we are getting thi...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1030,
    "percentScore" : 72.21627,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "coveo for sitecore+An entry with the same key already exists",
      "sysauthor" : "sekharitc",
      "sysurihash" : "1mG93eEVwfhWv1Pk",
      "urihash" : "1mG93eEVwfhWv1Pk",
      "numberofanswers" : 0,
      "sysuri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160349,
      "questionaskeddatestring" : "·\n            Feb 11, 2015 at 01:50 AM ·",
      "tags" : [ "coveoforsitecore" ],
      "sysconcepts" : "coveo ; exception ; entry ; sitecore ; PropertyStoreConfig ; SearchProvider ; Yogesh Kumar Sharma ; folder deleted ; PipelineArgsFactory ; IPipelineArgsFactory ; IIndexableWrapper ; CreateIndexableItem ; DocumentFactory ; B5965CDF4F6E ; ManagedPoolThread",
      "concepts" : "coveo ; exception ; entry ; sitecore ; PropertyStoreConfig ; SearchProvider ; Yogesh Kumar Sharma ; folder deleted ; PipelineArgsFactory ; IPipelineArgsFactory ; IIndexableWrapper ; CreateIndexableItem ; DocumentFactory ; B5965CDF4F6E ; ManagedPoolThread",
      "printableuri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517941966000,
      "permanentid" : "63c486777ce51e762408a67e8ace2374d239ccea276e7c37b9132363d140",
      "syslanguage" : [ "English" ],
      "transactionid" : 160349,
      "title" : "coveo for sitecore+An entry with the same key already exists",
      "date" : 1424044800000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "hasanswer" : "false",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Simon \u2666\u2666", "Simon \u2666\u2666", "Jean-François L'Heureux \u2666\u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5447398,
      "numberofcomments" : 3,
      "size" : 69862,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911577699,
      "acceptedanswers" : 0,
      "syssize" : 69862,
      "sysdate" : 1424044800000,
      "author" : "sekharitc",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>hi,</p> \n<p>i am getting following exception.Actually there is one folder deleted from sitecore and recreated. after that we are getting this issue.</p> \n<pre><code> ManagedPoolThread #12 09:01:41 ERROR An exception occurred while trying to process the item {54CE1313-2372-4D93-AAF7-B5965CDF4F6E} : An entry with the same key already exists.\n Exception: System.ArgumentException\n Message: An entry with the same key already exists.\n Source: System\n    at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)\n    at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)\n    at Sitecore.Data.Items.MediaItem.GetMetaData()\n    at Coveo.Framework.Items.MediaItemWrapper.GetMetaData()\n    at Coveo.SearchProvider.Documents.DocumentBuilder.SetMetadata(IItem p_Item, CoveoIndexableItem p_CoveoIndexableItem)\n    at Coveo.SearchProvider.Documents.DocumentBuilder.AddMetadata()\n    at Coveo.SearchProvider.Documents.DocumentFactory.CreateIndexableItem(IIndexableWrapper p_Indexable, IPipelineArgsFactory p_PipelineArgsFactory, PropertyStoreConfig p_PropertyStoreConfig)\n\n</code></pre> \n<p>Plz help how to fix this issue.</p> \n<p>Regards, Naga</p>\n                </div>",
      "sitemaplastmodified" : 1424044800000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517941966000,
      "questionnumber" : 4023,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "sekharitc",
      "sitename" : "Answers",
      "sysrowid" : 5447398,
      "uri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "coveo for sitecore+An entry with the same key already exists",
    "Uri" : "http://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "PrintableUri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "ClickUri" : "https://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/4023/coveo-for-sitecorean-entry-with-the-same-key-alrea.html",
    "Excerpt" : "coveo for sitecore+An entry with the same key already exists ... i am getting following exception.Actually there is one folder deleted from sitecore and recreated. ... after that we are getting thi...",
    "FirstSentences" : null
  }