{
    "title" : "The remote name could not be resolved: 'platform.cloud.coveo.com'",
    "uri" : "http://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "printableUri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "clickUri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "excerpt" : "I am trying to install Coveo Cloud trial to locally develop and configure Coveo but it fails at the point where I have to login into Coveo Cloud., After a succesful login with Google, I get the err...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1168,
    "percentScore" : 76.90204,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "The remote name could not be resolved: 'platform.cloud.coveo.com'",
      "sysauthor" : "Sjef Jenniskens",
      "sysurihash" : "iFUD9NdGRyiGJErz",
      "urihash" : "iFUD9NdGRyiGJErz",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160363,
      "questionaskeddatestring" : "·\n            Feb 07, 2017 at 08:20 AM ·",
      "tags" : [ "coveoforsitecore", "cloud", "installation", "platform", "login" ],
      "sysconcepts" : "Cloud trial ; platform ; remote ; login ; stack trace ; web request ; unhandled exception ; proxysetting ; execution ; flguillemette ; WebException",
      "concepts" : "Cloud trial ; platform ; remote ; login ; stack trace ; web request ; unhandled exception ; proxysetting ; execution ; flguillemette ; WebException",
      "printableuri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942994000,
      "permanentid" : "c4d25ea8044e2c9a24eed4aac94bcda23e9031560d3a83c6d29e4f13467a",
      "syslanguage" : [ "English" ],
      "transactionid" : 160363,
      "title" : "The remote name could not be resolved: 'platform.cloud.coveo.com'",
      "date" : 1486512000000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Sjef Jenniskens" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "François Lachance-Guillemette \u2666\u2666" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448742,
      "numberofcomments" : 1,
      "size" : 75918,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911579015,
      "acceptedanswers" : 1,
      "syssize" : 75918,
      "sysdate" : 1486512000000,
      "author" : "Sjef Jenniskens",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>I am trying to install Coveo Cloud trial to locally develop and configure Coveo but it fails at the point where I have to login into Coveo Cloud., After a succesful login with Google, I get the error message \"The remote name could not be resolved: '<a rel=\"nofollow\" href=\"http://platform.cloud.coveo.com\">platform.cloud.coveo.com</a>' \"</p> \n<p>The details of the error message are: Server Error in '/' Application.</p> \n<p>The remote name could not be resolved: '<a rel=\"nofollow\" href=\"http://platform.cloud.coveo.com\">platform.cloud.coveo.com</a>'</p> \n<p>Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. </p> \n<p>Exception Details: System.Net.WebException: The remote name could not be resolved: '<a rel=\"nofollow\" href=\"http://platform.cloud.coveo.com\">platform.cloud.coveo.com</a>'</p> \n<p>Source Error: </p> \n<p>An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</p> \n<p>Stack Trace: </p> \n<p>[WebException: The remote name could not be resolved: '<a rel=\"nofollow\" href=\"http://platform.cloud.coveo.com\">platform.cloud.coveo.com</a>'] System.Net.HttpWebRequest.GetResponse() +1743 Coveo.Framework.Utils.Rest.HttpClient.ExecuteRequest(String p_Url, Func`2 p_CreateRequest, Int64 p_CallId) +334</p> \n<p>[HttpClientException: Failed to obtain resource located at '<a rel=\"nofollow\" href=\"https://platform.cloud.coveo.com/rest/organizations'.\">https://platform.cloud.coveo.com/rest/organizations'.</a> See inner exception for details.] Coveo.Framework.Utils.Rest.HttpClient.HandleResponseException(WebException p_Exception, String p_Url, Int64 p_CallId) +392 Coveo.Framework.Utils.Rest.HttpClient.ExecuteRequest(String p_Url, Func`2 p_CreateRequest, Int64 p_CallId) +776 Coveo.Framework.Utils.Rest.HttpClient.GetRaw(String p_Url) +248 Coveo.Framework.Utils.Rest.HttpClient.Get(String p_Url) +127 Coveo.CloudPlatformClientBase.CloudPlatformClient.PerformPlatformCall(String p_HttpMethod, String p_OperationUri, String p_RequestContent) +453 Coveo.CloudPlatformClientBase.CloudPlatformClient.PerformPlatformCallWithErrorHandling(String p_RequestMethod, String p_RequestUri, String p_RequestContent) +263 Coveo.CloudPlatformClientBase.CloudPlatformClient.GetOrganizations() +347 Coveo.SearchProvider.Applications.Shell.Controls.ConfigureCoveoCloudOrganizationWizardFormPage.SetUpOrganizationList() +165 Coveo.SearchProvider.Applications.Shell.Controls.ConfigureCoveoCloudOrganizationWizardFormPage.OnPreRender(Object p_Sender, EventArgs p_E) +57 System.Web.UI.Control.OnPreRender(EventArgs e) +11937633 System.Web.UI.Control.PreRenderRecursiveInternal() +110 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Control.PreRenderRecursiveInternal() +207 System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2994 </p> \n<p>When I access \"<a rel=\"nofollow\" href=\"https://platform.cloud.coveo.com/\">https://platform.cloud.coveo.com/</a>\" via Chrome, I get redirected to \"<a rel=\"nofollow\" href=\"https://platform.cloud.coveo.com/admin/\">https://platform.cloud.coveo.com/admin/</a>\" and the following message is show \"You currently do not have access to any organizations.\"</p> \n<p>What am I doing wrong?</p>\n                </div>",
      "sitemaplastmodified" : 1486512000000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942994000,
      "questionnumber" : 10387,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "Sjef Jenniskens",
      "sitename" : "Answers",
      "sysrowid" : 5448742,
      "uri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "The remote name could not be resolved: 'platform.cloud.coveo.com'",
    "Uri" : "http://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "PrintableUri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "ClickUri" : "https://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/10387/the-remote-name-could-not-be-resolved-platformclou.html",
    "Excerpt" : "I am trying to install Coveo Cloud trial to locally develop and configure Coveo but it fails at the point where I have to login into Coveo Cloud., After a succesful login with Google, I get the err...",
    "FirstSentences" : null
  }