{
    "title" : "Exception while processing an item: -> Unable to connect to the remote server",
    "uri" : "http://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "printableUri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "clickUri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "excerpt" : "Exception while processing an item: -> Unable to connect to the remote server ... We are using free edition for coveo for sitecore and CES. ... Sitecore and coveo for sitecore installed on one mach...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1146,
    "percentScore" : 76.174355,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Exception while processing an item: -> Unable to connect to the remote server",
      "sysauthor" : "swamcts",
      "sysurihash" : "t0D6RWNT5HygXfpp",
      "urihash" : "t0D6RWNT5HygXfpp",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160360,
      "questionaskeddatestring" : "·\n            Sep 09, 2016 at 09:16 PM ·",
      "tags" : [ "exception" ],
      "sysconcepts" : "free edition ; remote server ; sitecore ; coveo ; installation ; Unable ; Exception ; configuration ; times successfully ; connected host ; search API ; searchprovider ; showconfig ; 2fLanguage ; 7EB29BD6DAD ; 2fdatabase",
      "concepts" : "free edition ; remote server ; sitecore ; coveo ; installation ; Unable ; Exception ; configuration ; times successfully ; connected host ; search API ; searchprovider ; showconfig ; 2fLanguage ; 7EB29BD6DAD ; 2fdatabase",
      "printableuri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942734000,
      "permanentid" : "b5f8c196a788657335650900ad14a1adbd67786e965c2324260bbc6903c2",
      "syslanguage" : [ "English" ],
      "transactionid" : 160360,
      "title" : "Exception while processing an item: -> Unable to connect to the remote server",
      "date" : 1473638400000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Diego" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "swamcts", "Diego" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448411,
      "numberofcomments" : 2,
      "size" : 74860,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578711,
      "acceptedanswers" : 0,
      "syssize" : 74860,
      "sysdate" : 1473638400000,
      "author" : "swamcts",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Hi, </p> \n<p>We are using free edition for coveo for sitecore and CES.</p> \n<p>Sitecore and coveo for sitecore installed on one machine. CES and Coveo search API is installed on one machine.</p> \n<p>Status: Diagonise page shows green.</p> \n<p>Show config url shows working fine [<a rel=\"nofollow\" href=\"http://xx//sitecore/admin/showconfig.aspx\">http://xx//sitecore/admin/showconfig.aspx</a>]</p> \n<p>Rest page getting response [<a rel=\"nofollow\" href=\"http://xx//\">http://xx//</a> /coveo/rest] - fine</p> \n<p>Issue:</p> \n<p>Exception while processing an item: -> Unable to connect to the remote server -> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.54.140.39:443 9/9/2016 10:14:06 AM | Uri to ignore for deletion : hostname- IAAPP-AS- 1S/Document:sitecore%3a%2f%2fdatabase%2fmaster%2fItemId%2f0FDE275D-205D-414B-A6B5-7EB29BD6DAD%2fLanguage%2fen%2fVersion</p> \n<p>Am not able to proceed further, indexing not completing. Please help me asap</p> \n<p>%2f1</p>\n                </div>",
      "sitemaplastmodified" : 1473638400000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942734000,
      "questionnumber" : 8952,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "swamcts",
      "sitename" : "Answers",
      "sysrowid" : 5448411,
      "uri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Exception while processing an item: -> Unable to connect to the remote server",
    "Uri" : "http://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "PrintableUri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "ClickUri" : "https://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/8952/exception-while-processing-an-item-unable-to-conne.html",
    "Excerpt" : "Exception while processing an item: -> Unable to connect to the remote server ... We are using free edition for coveo for sitecore and CES. ... Sitecore and coveo for sitecore installed on one mach...",
    "FirstSentences" : null
  }