{
    "title" : "Encryption Keys",
    "uri" : "http://answers.coveo.com/questions/7222/encryption-keys.html",
    "printableUri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
    "clickUri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/7222/encryption-keys.html",
    "excerpt" : "What causes the encryption keys to be regenerated? ... We have an instance that has now twice stopped working and outputting the error below. ... We have resolved the issue be re-entering the user ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1131,
    "percentScore" : 75.67419,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Encryption Keys",
      "sysauthor" : "renjohn",
      "sysurihash" : "ðdeTLAKQK7qLtPN2",
      "urihash" : "ðdeTLAKQK7qLtPN2",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160357,
      "questionaskeddatestring" : "·\n            Jan 22, 2016 at 10:06 AM ·",
      "tags" : [ "coveoforsitecore", "coveo" ],
      "sysconcepts" : "encrypted passwords ; coveo ; security ; servers ; trust relationship ; stopped working ; re-doing the configuration ; outputting the error ; SearchProvider",
      "concepts" : "encrypted passwords ; coveo ; security ; servers ; trust relationship ; stopped working ; re-doing the configuration ; outputting the error ; SearchProvider",
      "printableuri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942542000,
      "permanentid" : "4250a9d5418fc2f1e1c707a144d0bdff223b56b9055526d5f6783e45a3fc",
      "syslanguage" : [ "English" ],
      "transactionid" : 160357,
      "title" : "Encryption Keys",
      "date" : 1459900800000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "renjohn" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "dsoriano", "Jean-François L'Heureux \u2666\u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448143,
      "numberofcomments" : 2,
      "size" : 80602,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578444,
      "acceptedanswers" : 0,
      "syssize" : 80602,
      "sysdate" : 1459900800000,
      "author" : "renjohn",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>What causes the encryption keys to be regenerated? We have an instance that has now twice stopped working and outputting the error below. We have resolved the issue be re-entering the user identity (several time), restarting the security provider, re-doing the configuration for the coveo users in sitecore. When we see new encrypted passwords generated for the user, we can see the encryption keys have been updated and then we copy the settings and keys to all servers. The problem only goes away once the encryption key has been regenerated. This has cost me many hours of my life and downtime on production. I would like to know how I can prevent this in the future, and solve it more quickly moving forward.</p> \n<ul> \n <li><p> Sitecore 7.1 </p> </li> \n <li><p> Current Coveo for Sitecore version: 3.0.1123.0 </p> </li> \n <li><p> Current Sitecore version: 7.1.140324</p> </li> \n</ul> \n<p>Error in the logs:</p> \n<pre><code> Could not establish trust relationship for the SSL/TLS secure channel with authority '172.16.10.10:52810'. (Hide details)\n System.ServiceModel.Security.SecurityNegotiationException: Could not establish trust relationship for the SSL/TLS secure channel with authority '172.16.10.10:52810'. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.\n    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)\n    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)\n    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)\n    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)\n    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)\n    at System.Net.ConnectStream.WriteHeaders(Boolean async)\n    --- End of inner exception stack trace ---\n    at System.Net.HttpWebRequest.GetResponse()\n    at System.Net.HttpWebRequest.GetResponse()\n    at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)\n    --- End of inner exception stack trace ---\n \n Server stack trace: \n    at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)\n    at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)\n    at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)\n    at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)\n    at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)\n    at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)\n    at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)\n    at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)\n \n Exception rethrown at [0]: \n    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)\n    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)\n    at Coveo.Framework.CoveoSearchService.CoveoSearchService.GetSearchProviderFields(SearchSession Session)\n    at Coveo.SearchProvider.Applications.StateVerifier.VerifySearchService()\n    at Coveo.SearchProvider.Applications.StateVerifier.<>c__DisplayClass10.<GetSearchServiceState>b__f()\n    at Coveo.SearchProvider.Applications.BaseVerifier.VerifyComponent(Func`1 p_VerifyMethod, String p_ComponentName)\n\n</code></pre>\n                </div>",
      "sitemaplastmodified" : 1459900800000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942542000,
      "questionnumber" : 7222,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "renjohn",
      "sitename" : "Answers",
      "sysrowid" : 5448143,
      "uri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Encryption Keys",
    "Uri" : "http://answers.coveo.com/questions/7222/encryption-keys.html",
    "PrintableUri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
    "ClickUri" : "https://answers.coveo.com/questions/7222/encryption-keys.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/7222/encryption-keys.html",
    "Excerpt" : "What causes the encryption keys to be regenerated? ... We have an instance that has now twice stopped working and outputting the error below. ... We have resolved the issue be re-entering the user ...",
    "FirstSentences" : null
  }