{
    "title" : "Security cache unable to connect should display an \"ERROR\" in the logs",
    "uri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
    "printableUri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
    "clickUri" : "https://na61.salesforce.com/08732000000D09hAAC",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
    "excerpt" : "Currently, if the security cache is unable to connect to Salesforce because of bad credentials, it will only display a \"WARNING\" in the logs. ... This \"WARNING\" will contain all the necessary infor...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1206,
    "percentScore" : 78.143005,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Security cache unable to connect should display an \"ERROR\" in the logs",
      "sysurihash" : "5PIKFLhgakðnJSW5",
      "urihash" : "5PIKFLhgakðnJSW5",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"Idea\" uri=\"https://na61.salesforce.com/087/o\" /><parent name=\"08732000000D09hAAC\" uri=\"https://na61.salesforce.com/08732000000D09hAAC\" /></parents>",
      "sfid" : "08732000000D09hAAC",
      "sysuri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
      "systransactionid" : 161137,
      "sfcategories" : "Coveo Platform",
      "sfsystemmodstamp" : 1499979696000,
      "sfvotescore" : 1.90869966574232E-31,
      "sfcommunityname" : "Coveo Community",
      "sysconcepts" : "security cache ; login attempts ; server ; logs ; Salesforce ; email alerts ; providers separately ; eventually end ; enormous quantity ; kind of behavior ; credentials",
      "sfcreatorname" : "Eric Savoie",
      "concepts" : "security cache ; login attempts ; server ; logs ; Salesforce ; email alerts ; providers separately ; eventually end ; enormous quantity ; kind of behavior ; credentials",
      "printableuri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
      "documenttype" : "record",
      "sysindexeddate" : 1518187484000,
      "sfcreatedbyid" : "00560000003FMKhAAO",
      "permanentid" : "37630bcf88e984f6953bf8223d7d2cbf74b2500671027e57c8aadeb8cbb9",
      "syslanguage" : [ "English" ],
      "sfideaid" : "08732000000D09hAAC",
      "transactionid" : 161137,
      "title" : "Security cache unable to connect should display an \"ERROR\" in the logs",
      "date" : 1499979696000,
      "objecttype" : "Idea",
      "allmetadatavalues" : "{\"coveo_short_id\": [\"08732000000D09h\"], \"sflastmodifiedbyname\": [\"Eric Savoie\"], \"lastmodifieddate\": [1499979696], \"lastmodifiedby.id\": [\"00560000003FMKhAAO\"], \"community.createddate\": [1496347580], \"createdby.attribute.type\": [\"User\"], \"originalhtmlcharset\": [0], \"sfid\": [\"08732000000D09hAAC\"], \"createdby.lastmodifieddate\": [1484712659], \"sfishtml\": [true], \"sfcreatorsmallphotourl\": [\"https://c.na61.content.force.com/profilephoto/72960000000LuMU/T\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Security cache unable to connect should display an \\\"ERROR\\\" in the logs\"], \"lastmodifiedby.createddate__fiscal_month\": [7], \"sfvotetotal\": [10], \"source\": [\"Salesforce Public Items\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"Idea\\\" uri=\\\"https://na61.salesforce.com/087/o\\\" /><parent name=\\\"08732000000D09hAAC\\\" uri=\\\"https://na61.salesforce.com/08732000000D09hAAC\\\" /></parents>\"], \"detectedtitle\": [\"Currently, if the security cache is unable to connect to Salesforce because of bad credentials, it will only display a \\\"WARNING\\\" in the logs. This \\\"WARNING\\\" will contain all the necessary information to know what the problem is (401 unauthorized). However, since the security cache is triggering failed login attempts, and retrying when it's not able to, the Salesforce server will return an enormous quantity of failed login attempts errors if it's monitored. With some clients, it can even cause some performance issues. Also, the update will eventually end without having updated any security whatsoever because it never had access to the server. All this, without any means to receive an email alert from Coveo to know something's wrong.\"], \"lastmodifiedby.attribute.type\": [\"User\"], \"createdby.createddate_fiscalmonth\": [7], \"sfcommunityname\": [\"Coveo Community\"], \"coveo_url\": [\"https://na61.salesforce.com/08732000000D09hAAC\"], \"sfcreatedbyname\": [\"Eric Savoie\"], \"objecttypelabel\": [\"Idea\"], \"sfcommunityid\": [\"09a32000000XhryAAC\"], \"sfstatus\": [\"Submitted\"], \"ismerged\": [false], \"createdby.createddate__fiscal_month\": [7], \"coveo_connector_hasbinarydata\": [false], \"categories\": [\"Coveo Platform\"], \"lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000003FMKhAAO\"], \"lastmodifiedby.createddate_fiscalmonth\": [7], \"sfvotescore\": [1.90869966574232e-31], \"sfcreatorfullphotourl\": [\"https://c.na61.content.force.com/profilephoto/72960000000LuMU/F\"], \"clickableuri\": [\"https://na61.salesforce.com/08732000000D09hAAC\"], \"coveo_record_size\": [2], \"sftitle\": [\"Security cache unable to connect should display an \\\"ERROR\\\" in the logs\"], \"body__html_stripped\": [\"Currently, if the security cache is unable to connect to Salesforce because of bad credentials, it will only display a \\\"WARNING\\\"\\u00a0in the logs. This \\\"WARNING\\\" will contain all the necessary information to know what the problem is (401 unauthorized). However, since the security cache is triggering failed login attempts, and retrying when it's not able to, the Salesforce server will return an enormous quantity of failed login attempts errors if it's monitored. With some clients, it can even cause some performance issues. Also, the update will eventually end without having updated any security whatsoever because it never had access to the server. All this, without any means to receive an email alert from Coveo to know something's wrong.\\n \\n\\n We believe the kind of problem should at least trigger an \\\"ERROR\\\"\\u00a0in the logs in order to be easily traceable and eligible to email alerts. It could even go as far as preventing the security cache from updating. However this kind of behavior would probably be more realistic if we could update each security providers separately.\\n\"], \"sfcurrencyisocode\": [\"USD\"], \"createdby.id\": [\"00560000003FMKhAAO\"], \"sfcreatorname\": [\"Eric Savoie\"], \"community.name\": [\"Coveo Community\"], \"contenttype\": [\"binarydata\"], \"sfismerged\": [false], \"lastmodifiedby.createddate_fiscalquarter\": [2], \"createddate\": [1499979696], \"body\": [\"Currently, if the security cache is unable to connect to Salesforce because of bad credentials, it will only display a \\\"WARNING\\\"\\u00a0in the logs. This \\\"WARNING\\\" will contain all the necessary information to know what the problem is (401 unauthorized). However, since the security cache is triggering failed login attempts, and retrying when it's not able to, the Salesforce server will return an enormous quantity of failed login attempts errors if it's monitored. With some clients, it can even cause some performance issues. Also, the update will eventually end without having updated any security whatsoever because it never had access to the server. All this, without any means to receive an email alert from Coveo to know something's wrong.\\n \\n\\n We believe the kind of problem should at least trigger an \\\"ERROR\\\"\\u00a0in the logs in order to be easily traceable and eligible to email alerts. It could even go as far as preventing the security cache from updating. However this kind of behavior would probably be more realistic if we could update each security providers separately.\\n\"], \"sfcreatedbyid\": [\"00560000003FMKhAAO\"], \"createdby.coveo_record_size\": [2], \"votetotal\": [10], \"community.attribute.url\": [\"/services/data/v34.0/sobjects/Community/09a32000000XhryAAC\"], \"createdby.createddate__fiscal_year\": [\"2015\"], \"conversionstate\": [0], \"language\": [\"English\"], \"createdby.createddate_fiscalyear\": [\"2015\"], \"lastmodifiedby.createddate__fiscal_quarter\": [2], \"community.coveo_record_size\": [2], \"votescore\": [1.90869966574232e-31], \"systemmodstamp\": [1499979696], \"objecttype\": [\"Idea\"], \"lastmodifiedby.createddate_fiscalweek\": [15], \"numcomments\": [0], \"attribute.type\": [\"Idea\"], \"originaluri\": [\"http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC\"], \"convertertype\": [\"TYPE_TXT\"], \"filetype\": [\"SalesforceItem\"], \"hashtmlversion\": [true], \"lastmodifiedby.name\": [\"Eric Savoie\"], \"objecttypelabelplural\": [\"Ideas\"], \"createdby.createddate\": [1404760379], \"createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000003FMKhAAO\"], \"sfisdeleted\": [false], \"extractedsize\": [2152], \"size\": [3736], \"generateexcerpt\": [true], \"createdby.createddate__fiscal_week\": [15], \"documenttype\": [\"record\"], \"isdeleted\": [false], \"lastmodifiedby.createddate__fiscal_pretty_quarter\": [\"2015-Q2\"], \"mappingtype\": [\"Idea\"], \"lastmodifiedby.createddate__fiscal_year\": [\"2015\"], \"community.lastmodifieddate\": [1496347580], \"attribute.url\": [\"/services/data/v34.0/sobjects/Idea/08732000000D09hAAC\"], \"lastmodifiedby.createddate_fiscalyear\": [\"2015\"], \"createdby.createddate__fiscal_pretty_quarter\": [\"2015-Q2\"], \"coveo_objecttype\": [\"Idea\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC\"], \"fileextension\": [\"\"], \"lastmodifiedby.createddate__fiscal_week\": [15], \"createdby.createddate_fiscalweek\": [15], \"sfcreateddate\": [1499979696], \"creatorsmallphotourl\": [\"https://c.na61.content.force.com/profilephoto/72960000000LuMU/T\"], \"sfsystemmodstamp\": [1499979696], \"createdby.createddate_fiscalquarter\": [2], \"coveo_effective_modstamp\": [1499979696], \"concepts\": [\"security cache ; login attempts ; server ; logs ; Salesforce ; email alerts ; providers separately ; eventually end ; enormous quantity ; kind of behavior ; credentials\"], \"lastmodifiedby.lastmodifieddate\": [1484712659], \"sfideaid\": [\"08732000000D09hAAC\"], \"coveo_organization_id\": [\"00D3000000007r2\"], \"sflastmodifieddate\": [1499979696], \"createdby.systemmodstamp\": [1518155898], \"detectedlanguage\": [1], \"currencyisocode\": [\"USD\"], \"id\": [\"08732000000D09hAAC\"], \"createdby.name\": [\"Eric Savoie\"], \"ishtml\": [true], \"lastmodifiedby.coveo_record_size\": [2], \"sfnumcomments\": [0], \"status\": [\"Submitted\"], \"createdby.createddate__fiscal_quarter\": [2], \"sfcategories\": [\"Coveo Platform\"], \"collection\": [\"default\"], \"date\": [1499979696], \"community.systemmodstamp\": [1496347580], \"lastmodifiedby.createddate\": [1404760379], \"community.id\": [\"09a32000000XhryAAC\"], \"lastmodifiedby.systemmodstamp\": [1518155898], \"connectortype\": [\"Salesforce2\"], \"creatorname\": [\"Eric Savoie\"], \"sflastmodifiedbyid\": [\"00560000003FMKhAAO\"], \"creatorfullphotourl\": [\"https://c.na61.content.force.com/profilephoto/72960000000LuMU/F\"], \"sitename\": [\"Community\"], \"community.attribute.type\": [\"Community\"], \"sfbody\": [\"Currently, if the security cache is unable to connect to Salesforce because of bad credentials, it will only display a \\\"WARNING\\\"\\u00a0in the logs. This \\\"WARNING\\\" will contain all the necessary information to know what the problem is (401 unauthorized). However, since the security cache is triggering failed login attempts, and retrying when it's not able to, the Salesforce server will return an enormous quantity of failed login attempts errors if it's monitored. With some clients, it can even cause some performance issues. Also, the update will eventually end without having updated any security whatsoever because it never had access to the server. All this, without any means to receive an email alert from Coveo to know something's wrong.\\n \\n\\n We believe the kind of problem should at least trigger an \\\"ERROR\\\"\\u00a0in the logs in order to be easily traceable and eligible to email alerts. It could even go as far as preventing the security cache from updating. However this kind of behavior would probably be more realistic if we could update each security providers separately.\\n\"], \"permanentid\": [\"37630bcf88e984f6953bf8223d7d2cbf74b2500671027e57c8aadeb8cbb9\"]}",
      "sflastmodifiedbyid" : "00560000003FMKhAAO",
      "sfvotetotal" : 10.0,
      "syssfid" : "08732000000D09hAAC",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Security cache unable to connect should display an \"ERROR\" in the logs",
      "rowid" : 5491773,
      "syssfcreatedbyid" : "00560000003FMKhAAO",
      "size" : 3736,
      "sysdocumenttype" : "record",
      "sfcreateddate" : 1499979696000,
      "clickableuri" : "https://na61.salesforce.com/08732000000D09hAAC",
      "syssource" : "Salesforce Public Items",
      "orderingid" : 212384990660370577,
      "syssize" : 3736,
      "sysdate" : 1499979696000,
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"Idea\" uri=\"https://na61.salesforce.com/087/o\" /><parent name=\"08732000000D09hAAC\" uri=\"https://na61.salesforce.com/08732000000D09hAAC\" /></parents>",
      "sfismerged" : "false",
      "sfcurrencyisocode" : "USD",
      "sfstatus" : "Submitted",
      "sfnumcomments" : 0,
      "syssfcreateddate" : 1499979696000,
      "sflastmodifieddate" : 1499979696000,
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sflastmodifiedbyname" : "Eric Savoie",
      "collection" : "default",
      "syssourcetype" : "Salesforce",
      "sfbody" : "Currently, if the security cache is unable to connect to Salesforce because of bad credentials, it will only display a \"WARNING\" in the logs. This \"WARNING\" will contain all the necessary information to know what the problem is (401 unauthorized). However, since the security cache is triggering failed login attempts, and retrying when it's not able to, the Salesforce server will return an enormous quantity of failed login attempts errors if it's monitored. With some clients, it can even cause some performance issues. Also, the update will eventually end without having updated any security whatsoever because it never had access to the server. All this, without any means to receive an email alert from Coveo to know something's wrong.\n \n\n We believe the kind of problem should at least trigger an \"ERROR\" in the logs in order to be easily traceable and eligible to email alerts. It could even go as far as preventing the security cache from updating. However this kind of behavior would probably be more realistic if we could update each security providers separately.\n",
      "indexeddate" : 1518187484000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcommunityid" : "09a32000000XhryAAC",
      "sfcreatedbyname" : "Eric Savoie",
      "sysclickableuri" : "https://na61.salesforce.com/08732000000D09hAAC",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "syssfstatus" : "Submitted",
      "sfishtml" : "true",
      "sitename" : "Community",
      "sfcreatorsmallphotourl" : "https://c.na61.content.force.com/profilephoto/72960000000LuMU/T",
      "sysrowid" : 5491773,
      "sfcreatorfullphotourl" : "https://c.na61.content.force.com/profilephoto/72960000000LuMU/F",
      "uri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
      "syscollection" : "default"
    },
    "Title" : "Security cache unable to connect should display an \"ERROR\" in the logs",
    "Uri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
    "PrintableUri" : "http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
    "ClickUri" : "https://na61.salesforce.com/08732000000D09hAAC",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/object:Idea/record:08732000000D09hAAC",
    "Excerpt" : "Currently, if the security cache is unable to connect to Salesforce because of bad credentials, it will only display a \"WARNING\" in the logs. ... This \"WARNING\" will contain all the necessary infor...",
    "FirstSentences" : null
  }